name: tpsm++

dataset_params:
  root_dir: ../vox
  frame_shape: null
  id_sampling: True
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

loss_params:
  channels: ${model.model_params.common_params.num_channels}
  scales: [1, 0.5, 0.25, 0.125]
  loss_weights:
    reconstruction: 1
    perceptual: 1
    equivariance: 1
    warp: 1
    bg: 1

transform_params:
  sigma_affine: 0.05
  sigma_tps: 0.005
  points_tps: 5

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'

train_avd_params:
  num_epochs: 200
  num_repeats: 300
  batch_size: 256
  dataloader_workers: 24
  checkpoint_freq: 50
  epoch_milestones: [140, 180]
  lr: 1.0e-3
  lambda_shift: 1
  random_scale: 0.25

train_params:
  seed: 42
  num_epochs: 100
  num_repeats: 75
  optimizer:
    _partial_: true
    _target_: bitsandbytes.optim.Adam8bit
    lr: 2.0e-4
    betas: [0.5, 0.999]
  lr_scheduler:
    _partial_: true
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [70, 90]
    gamma: 0.1
  batch_size: 8
  accumulate_grad_batches: 8
  dataloader_workers: 8
  dropout_epoch: 35
  dropout_maxp: 0.3
  dropout_startp: 0.1
  dropout_inc_epoch: 10
  bg_start: 10

model:
  _target_: models.etps.ETPS
  model_params:
    common_params:
      num_tps: 10
      num_channels: 3
      bg: True
      multi_mask: True
    generator_params:
      block_expansion: 64
      max_features: 512
      num_down_blocks: 3
    dense_motion_params:
      block_expansion: 32
      max_features: 512
      num_blocks: 5
      scale_factor: 0.25
    kp_detector_params:
      scale_factor: 1
    bg_predictor_params:
      scale_factor: 1
    avd_network_params:
      id_bottle_size: 128
      pose_bottle_size: 128
  loss_params: ${loss_params}
  train_params: ${train_params}
  transform_params: ${transform_params}
  visualizer_params: ${visualizer_params}

datamodule:
  _target_: modules.data.datamodule.FrameDataModule
  ds_params: ${dataset_params}
  num_repeats: ${train_params.num_repeats}
  batch_size: ${train_params.batch_size}
  num_workers: ${train_params.dataloader_workers}

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  name: ${name}
  project: tpsm++
  offline: false

trainer:
  _target_: lightning.pytorch.Trainer
  precision: bf16-mixed
  accelerator: gpu
  accumulate_grad_batches: ${train_params.accumulate_grad_batches}
  logger: ${logger}
  max_epochs: ${train_params.num_epochs}
  log_every_n_steps: 1
  callbacks:
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: 2
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch